version: '3'
services:
  web:
    image: ambro01/nanoporeqc_app 
    ports:
    - 8080:8080
    links:
    - db:qc_db
    container_name: nanoporeqc_app
  db:
    image: ambro01/nanoporeqc_db
    ports:
    - 3307:3306
    container_name: nanoporeqc_db
