version: '3'
services:
  web:
    image: ambro01/nanoporeqc_app 
    ports:
    - 8080:8080
    depends_on:
    - db
    links:
    - db:qc_db
    container_name: nanoporeqc_app
  db:
    image: ambro01/nanoporeqc_db
    container_name: nanoporeqc_db
    command: --max_allowed_packet=32505856
    volumes:
       - db_data:/var/lib/mysql
volumes:
    db_data:
